### ISSUE TITLE
HTML title not set properly for first page load

### ISSUE THREAD

**Issue by dartar** [Wikidata/SQID#103]
To improve discoverability, SEO, and usability, the item label should be exposed in the HTML title tag, e.g.

http://tools.wmflabs.org/sqid/#/view?id=P1341&lang=en

currently displays:
**P1341 - SQID**

should be something like:
**Italian Chamber of Deputies ID (P1341) - SQID**

**Comment by mkroetzsch** [comment]
This seems to be a bug. If you click on any of the links to other items on the page, you will see that the title is displayed correctly there. (Whether any search engine can properly index such dynamically generated pages is another question. I don't know if this works, even if we fix it for human readers.)

**Comment by mkroetzsch** [comment]
Some investigation suggested that there might be a race condition in the parallel processing during the first page load here. We have, however, not yet been able to find a reliable fix for this behavior. This bug is not actively investigated at the moment, so suggestions are welcome.
