### ISSUE TITLE
Updating the statistics?

### ISSUE THREAD

**Issue by Sadads** [Wikidata/SQID#114]
Hey, it looks like the dumps have been delayed from https://tools.wmflabs.org/sqid/#/status ? Can you update this data, I need it for various projects.

**Comment by mkroetzsch** [comment]
Yes, I usually do this manually, but was busy in recent weeks ... I will soon update. The property and class data auto-updates every hour, so this is just about the general statistics.

**Comment by mkroetzsch** [comment]
It's really been a while but the statistics have now been updated. There is still no automated process in place to ensure that it will keep happening (but at least the processing pipeline is functional again).

**Comment by mmarx** [comment]
What is missing to automate these updates?

**Comment by mkroetzsch** [comment]
A little script should do this. Nothing major. This would be quite important to solve. See also #134

**Comment by mmarx** [comment]
As of fc45a200b40a85bbeec80293e4edbb20acfd90c3, dump processing is now fully automated.
