### ISSUE TITLE
PrimarySources suggestions can't be rejected on Chrome

### ISSUE THREAD

**Issue by abartov** [Wikidata/SQID#118]
Clicking the little [x] does not dismiss the suggestion, but instead collapses/expands the details.

**Comment by mkroetzsch** [comment]
This might be due to a conflict in the handling of click events, but this surely has been tested on Chrome originally, so it might be new. Could you also post which version of Chrome you are using and which page the problem can be seen on?

**Comment by abartov** [comment]
Chrome version 59.0.3071.86 (Official Build) (64-bit) on Linux.
I saw the behavior on e.g. http://tools.wmflabs.org/sqid/#/view?id=Q151872
(try [correctly] rejecting the suggested "Judaism".)

**Comment by mkroetzsch** [comment]
Indeed, I can confirm this behaviour on my machine, with almost the same version of Chromium. I wonder if this affects the accept and reject buttons in all cases now.

**Comment by guenthermi** [comment]
For some reason the userinfo promise has no .success() and .error() methods. This method is deprecated anyway and it is recommend to use .then() instead. There might be more places where these functions are used. So maybe this code should be refactored as well.

**Comment by mmarx** [comment]
It seems like this will need some more refactoring anyway to integrate the inferred statements; I'll keep that in mind, thanks.
