### ISSUE TITLE
SQID dump and get links on Property P4159

### ISSUE THREAD

**Issue by salgo60** [Wikidata/SQID#125]
I am introducing SQID to people at WeRelate would be nice to get a new dump so the value of P4159 is clickable example Q202266

**Comment by mmarx** [comment]
This is a duplicate of #114.

**Comment by mkroetzsch** [comment]
Fixed by recent data update (requires reload, possibly hard reload).

**Comment by salgo60** [comment]
Could we get a new reload I 
https://tools.wmflabs.org/sqid/#/view?id=Q4935959&lang=en

P4819 is not clickable

**Comment by mmarx** [comment]
Fixed.
