### ISSUE TITLE
 Some properties do not show up in list of properties

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Wikidata/SQID#132]
e.g. https://tools.wmflabs.org/sqid/#/browse?type=properties
does not show https://www.wikidata.org/wiki/Property:P698 (PMID)

This was originally posted at https://github.com/Wikidata/Wikidata-Toolkit/issues/363 , since I could not find a link from SQID to here (see #131 ).

**Comment by mmarx** [comment]
Fixed.
