### ISSUE TITLE
Outside any named section - top area - empty "subclass of:" but Wikidata has a claim

### ISSUE THREAD

**Issue by annainfo** [Wikidata/SQID#136]
https://tools.wmflabs.org/sqid/#/view?id=Q11446
ship (Q11446)
large buoyant watercraft
subclass of:
instance of: ship is a(n) ship type

In Wikidata:
subclass of: watercraft, vessel

**Comment by mmarx** [comment]
I can't reproduce this:

```
ship (Q11446)
large buoyant watercraft
subclass of: every ship is also a(n) watercraft, vessel
instance of: ship is a(n) ship type
```

**Comment by mmarx** [comment]
Okay, after some playing around, it seems that this only happens on the first load of a page. This might be related to #103.

**Comment by mmarx** [comment]
No longer present in the new codebase.
