### ISSUE TITLE
Make sure clients can get json updates

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/SQID#30]
Browsers are caching the json data files and they might only be updated on an extra-hard reload (something like "clear cache and reload" in Chrome). We should ensure that a normal hard reload suffices. Ideas:
- Use a cache manifest
- Change the file names on update and the HTML to include the current names.
- Make javascript actively check the statistics file once in a while and trigger an update from there (can we bypass the browser cache from javascript somehow? Some caching on browser level would still be useful, e.g., to avoid having to reload the json in every tab)

**Comment by mmarx** [comment]
The new code always includes a timestamp in statistics requests (initially 0), and keeps the time of the last refresh. After enough time has elapsed, the statistics metadata file is fetched with the current time as new timestamp (to bypass the cache), and the timestamps therein are used to decide whether to invalidate the timestamps for the other statistics files. Until that happens, requests will use the last timestamp to profit from the browser cache.
