### ISSUE TITLE
User control for number of results per page

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/SQID#57]
It is sometimes handy to show a big number of results per page (e.g., to use browsers text search for a particular string in descriptions). It would be good if the pager could support this and the query vuew could have controls to select how many results to show per page. A few choices would be enough, maybe: 15 (default, fits most screens), 50 (max. number of labels that can be fetched in one API request), 1000 (if this still works fast enough in browsers, otherwise maybe use 500 or 250 as a max).

This choice would be the same no matter how queries are created (run mode or query builder). The control for this should use only little space.

**Comment by arsylum** [comment]
This is now implemented as a directive for use within `PaginationController`. I used a hybrid widget that allows selection of proposed values (default 15,50,1000) as well as entering arbitrary numbers.

Possible values are currently enforced to a range of [3;2000]. While 2000 is pushing it, the app still performs surprisingly responsive with 1000 rows. I have a decent amount of RAM though.

It's not unthinkable to allow higher values as well, but that would call for some safety measure so users won't accidentally freeze their browser.
