### ISSUE TITLE
Use uib-pagination

### ISSUE THREAD

**Issue by arsylum** [Wikidata/SQID#80]
I just now discovered the convenience of the `uib-pagination` directive from `ui.bootstrap` which we depend on anyway. It can be used like this: (see bef1a9e1a722a31cbbdf2c09d84f43a814b3c8e4)
    
    <nav><uib-pagination 
        total-items="qui.pagination.numItems"
        items-per-page="qui.pagination.tableSize"
        ng-model="qui.pagination.activePage"
        max-size="qui.pagination.pageSelectorSize"
        previous-text="&laquo;"
        next-text="&raquo;"
        class="pagination-sm"
        boundary-link-numbers="true"
        ng-change="qui.pagination.setPage()"
     ></uib-pagination></nav>
This directive is preferable to the previous markup since it provides more features and is easier to read. 

Also once the `PaginationController`'s own pagination model is no longer used, that logic can be removed (which is about half of the code volume of pagination.controller).

**Comment by mkroetzsch** [comment]
I have assigned @guenthermi now since this was marked as belonging to Browse. Or is this a change that should be done in the PaginationController instead? Feel free to re-assign the task as suitable.

**Comment by arsylum** [comment]
Actually I think I will make a wrapper directive for this as an even cleaner solution, since many of the arguments would be the same throughout the application.

@guenthermi : Please wait with adaption / implementation until the directive is ready and merged .

**Comment by arsylum** [comment]
I merged an update to the pagination code that brings 3 new directives that can be used within the scope of a `PaginationController`:

1. `<table-size-selector></table-size-selector>` is a widget for selecting the number of rows that should be displayed on a page. Proposed values can be selected from a dropdown or entered manually. Allowed range [3-2000]. It has a float: right; styling applied.
2. `<pagination-index-range></pagination-index-range>` displays current range of result indices and number of total results. It's not very useful yet for lack of customizability.
3. `<nav pagination="$scope.pagination"></nav>` is a wrapper for the uib-pagination widget, that hooks it up with the `PaginationController`.

Please adapt the pagination nav in `browse.html` to the new directive (3), so the obsolete pagination logic can be dropped. The other two are not really necessary but we might consider to include the table-size-selector uniformly in all paginations.

**Comment by arsylum** [comment]
merged pull request
