### ISSUE TITLE
Leftover jQuery call

### ISSUE THREAD

**Issue by arsylum** [Wikidata/SQID#81]
There is a piece of code in [`sqid.module`](https://github.com/Wikidata/WikidataClassBrowser/blob/master/src/app/sqid.module.js) (from former `app/app`) that apparently is used nowhere:
`$("[data-toggle=popover]").popover({html:true});`

From what I can tell it's a jquery-ui feature, but since I cannot find markup that would be affected by it I guess it should be deleted.

Note that there also is [`uib-popover`](https://angular-ui.github.io/bootstrap/#/popover).

**Comment by mkroetzsch** [comment]
I have always been using uib-popover in my code. Maybe @guenthermi can comment.

**Comment by mkroetzsch** [comment]
Is this still open? Should be a small thing to fix.

**Comment by arsylum** [comment]
Maybe it didn't even warrant an issue. I just wanted to make sure I'm not missing something relevant. A bit of digging reveals it's actually a relic from c2246c52a53914b1a9ba1d8e9d9afc089e23109e. Not sure why it was added together with the bootstap-ui dependency, maybe it's related.

**Comment by mkroetzsch** [comment]
I deleted the call and pushed to master.
