### ISSUE TITLE
Set HTML title to indicate current view and content

### ISSUE THREAD

**Issue by nichtich** [Wikidata/SQID#84]
Multiple SQID browser tabs with different classes and properties all have same title. The title should be adjusted dynamically to the currently selected class or property.

**Comment by mkroetzsch** [comment]
Yes, this is a small but important thing that was on my implicit todo for a while now (I was surprised we did not have an issue yet). The main challenge there is that I don't know how to do this.

@arsylum @guenthermi Any idea how to set the HTML title attribute from a controller? Do we need to extend the angular-controlled part of the page to include the title, or could we use directives/angular elements up there already?

**Comment by mkroetzsch** [comment]
This should be solved in master and also online now. Maybe recheck since I am on such a slow connection that I cannot load the application without timeout.
