### ISSUE TITLE
Authority RePEc (P2428) missing

### ISSUE THREAD

**Issue by jneubert** [Wikidata/SQID#91]
P2428, the author identifier from Research Papers for Economics (RePEc), seems to be missing in the rightbar (Identifiers), nor is it present.

Example: http://tools.wmflabs.org/sqid/#/view?id=Q502557 vs. https://www.wikidata.org/wiki/Q502557

Would be great to have it there - at ZBW, we are discussing if we can contribute the mapping to RePEc, in order to also gain indirect mappings to GND and many other identifers.

**Comment by mkroetzsch** [comment]
I am seeing the RePEc short id in the identifier box on the right of http://tools.wmflabs.org/sqid/#/view?id=Q502557

Can you find RePEc under http://tools.wmflabs.org/sqid/#/browse?type=properties ? If not, then maybe your browser has cached an older version of the property list and needs to be refreshed. You can try Shift+CTRL+R to do this. If this fails, please let us know which browser you are using.

**Comment by jneubert** [comment]
Thanks, that fixed it.
