### ISSUE TITLE
White space at page bottom

### ISSUE THREAD

**Issue by arsylum** [Wikidata/SQID#92]
Picking up from #90

> Note: we need to rethink the white space at the page bottom. It is there to ensure that there is always a scroll bar (otherwise the layout may jump if one expands something that makes the page longer)

If this is the only reason for the white space then something like `overflow-y: scroll` on the `<body>` (or the app-wrapping `<div>`) is probably a more convenient solution.

**Comment by mkroetzsch** [comment]
Done and pushed to master.
