### ISSUE TITLE
where is the java program to compute statistics ?

### ISSUE THREAD

**Issue by dachary** [Wikidata/SQID#93]

**Comment by mkroetzsch** [comment]
The program is in the branch "sqid-helper" of [Wikidata Toolkit](https://github.com/Wikidata/Wikidata-Toolkit). The main code is in [SchemaUsageAnalyzer.java](https://github.com/Wikidata/Wikidata-Toolkit/blob/sqid-helper/wdtk-client/src/main/java/org/wikidata/wdtk/client/SchemaUsageAnalyzer.java). The code is invoked through by using the command-line client (running the client will show a help message that includes this action).

**Comment by dachary** [comment]
@mkroetzsch thanks for the hint :-) I proposed to add it to the README file so that others can find it as well ( https://github.com/Wikidata/SQID/pull/94 ).
