### ISSUE TITLE
SQID front page is blank on Safari 9.1.1

### ISSUE THREAD

**Issue by Tpt** [Wikidata/SQID#99]
I get the error:
`SyntaxError: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration.` from dist.min.js line 75739.

This line is `var searchEntities = function(str, lang='en', limit=7) {`.

The error is raised because argument default values are not supported by other browsers than Chrome 49+ and Firefox 15+

**Comment by mkroetzsch** [comment]
@guenthermi If I am not mistaken, this is part of your code for the entity search. Could you please avoid this? In general, I think default parameters do not necessarily lead to good code quality, especially when used on internal (private) functions.

**Comment by mkroetzsch** [comment]
@Tpt The online code is also updated now. Please verify that it works correctly for you (may require shit+reload in browser to make sure you get the new code).
